# Generated by Django 5.2.8 on 2025-11-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captcha',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(help_text='Employee who marked attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='faceapp.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Present', help_text='Attendance status', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when attendance was marked'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='Unique identifier for the employee', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(help_text='Full name of the employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(help_text='Store facial patterns as JSON string'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the employee was registered'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='faceapp_att_timesta_377c31_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'timestamp'], name='faceapp_att_employe_829949_idx'),
        ),
    ]
