# Generated by Django 5.2.8 on 2025-11-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_delete_captcha_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEmployeeMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Employee Map',
                'verbose_name_plural': 'External Employee Maps',
                'ordering': ['-created_at'],
            },
        ),
    ]
